if(EMSCRIPTEN)
    add_library(z INTERFACE)
    add_library(ZLIB::ZLIB ALIAS z)
	target_compile_options(z INTERFACE "SHELL:-s USE_ZLIB=1")
	target_link_libraries(z INTERFACE "-s USE_ZLIB=1")
    return()
else()
    message(FATAL_ERROR "Not in Emscripten environment!")
endif()