if(EMSCRIPTEN)
    add_library(png INTERFACE)
    add_library(PNG::PNG ALIAS png)
	target_compile_options(png INTERFACE "SHELL:-s USE_LIBPNG=1")
	target_link_libraries(png INTERFACE "-s USE_LIBPNG=1")
    return()
else()
    message(FATAL_ERROR "Not in Emscripten environment!")
endif()