Document: openc2e
Title: Debian openc2e Manual
Author: <insert document author here>
Abstract: This manual describes what openc2e is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/openc2e/openc2e.sgml.gz

Format: postscript
Files: /usr/share/doc/openc2e/openc2e.ps.gz

Format: text
Files: /usr/share/doc/openc2e/openc2e.text.gz

Format: HTML
Index: /usr/share/doc/openc2e/html/index.html
Files: /usr/share/doc/openc2e/html/*.html

  
