#!/bin/zsh
# vim: set ft=zsh :

set -e
set -u

default_git_base="git://github.com/ccdevnet/openc2e.git"
default_ppasuffix=ppa0
set -A suites intrepid jaunty karmic

### You shouldn't need to modify anything below here

git_root="$(D="$(git rev-parse --git-dir)"; test -n "$D" && cd "$D" && echo "$PWD")"

git_base="${git_base:-$default_git_base}"
ppasuffix="${default_ppasuffix:-ppa0}"

echo "=== Preparing git checkout ==="
tempdir=`mktemp -d`
echo "Using $tempdir for temporary work."
pushd $tempdir

if test -z "$tempdir"; then
	echo "Starting directory doesn't look like an openc2e checkout."
	echo "Will check out from scratch."
	mkdir openc2e
	pushd openc2e
	git init
	popd
else
	echo "Cloning original repository."
	git clone -s $git_root openc2e
fi

echo "=== Updating git checkout ==="
pushd openc2e
git remote add src $git_base
git fetch src
git checkout -q refs/remotes/src/master

describe_ver="$(git-describe --tags)-$ppasuffix"
raw_ver="$(git-log -1 --pretty=format:\%H)"
echo "=== Checked out version $describe_ver ==="

echo "=== Building orig.tar.gz ==="
git-archive --format=tar --prefix="openc2e-$describe_ver/" HEAD | gzip -9c > "$tempdir/openc2e_$describe_ver.orig.tar.gz"
popd

echo "=== Building package ==="
checkout=openc2e-$describe_ver
mv openc2e $checkout
rm "$checkout/.git" -rf

cp $checkout/debian/changelog $tempdir/changelog.orig


suiteidx=0
for suite in $suites; do
	suiteidx=$(($suiteidx + 1))
	pushd $checkout/debian
	cp -f $tempdir/changelog.orig changelog
	debversion="$describe_ver""-1~$suiteidx$suite"
	debchange -v $debversion -D UNRELEASED -b "Automatic checkout of commit $raw_ver"
	cd ..
	dpkg-buildpackage -sa -rfakeroot -S -us -uc
	popd
	debsign openc2e_${debversion}_source.changes

	sed "s/SUITE/$suite/" < $tempdir/$checkout/debian/dput.cf > $tempdir/dput.cf
	dput -c $tempdir/dput.cf ccdevnet-ppa openc2e_${debversion}_source.changes
done

rm -rf $tempdir
