//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by C2ERoomEditor.rc
//
#define IDB_APPLY                       3
#define IDD_ABOUTBOX                    100
#define CG_IDD_PROGRESS                 102
#define CG_IDS_PROGRESS_CAPTION         103
#define IDB_LIGHTBULB                   104
#define IDD_TIP                         105
#define CG_IDS_TIPOFTHEDAY              106
#define CG_IDS_TIPOFTHEDAYMENU          107
#define CG_IDS_DIDYOUKNOW               108
#define CG_IDS_FILE_ABSENT              109
#define CG_IDP_FILE_CORRUPT             110
#define CG_IDS_TIPOFTHEDAYHELP          111
#define ID_TIMER                        112
#define IDR_MAINFRAME                   128
#define IDR_C2EROOTYPE                  129
#define IDS_ACTION_NONE                 130
#define IDD_PROPERTIES                  130
#define IDS_ACTION_ADD_ROOM             131
#define IDC_ZOOM                        131
#define IDS_ACTION_ADD_METAROOM         132
#define IDD_PROPERY_TYPES               132
#define IDS_ACTION_REMOVE_ROOM          133
#define IDD_PROPERTY_TYPE               133
#define IDS_ACTION_REMOVE_METAROOM      134
#define IDS_ACTION_MODIFY_ROOM          135
#define IDD_EMPTY_CHILD                 135
#define IDS_ACTION_MODIFY_METAROOM      136
#define IDS_UNDO                        137
#define IDD_ROOM_PROPERTIES             137
#define IDS_REDO                        138
#define IDS_ACTION_MOVE_METAROOM        139
#define IDC_ADD_ROOM                    139
#define IDS_ACTION_ROOM_PROPERTY        140
#define IDC_ADD_METAROOM                140
#define IDS_ACTION_MOVE_ROOM            141
#define IDR_ZOOM_MENU                   141
#define IDR_SELECT_MENU                 142
#define IDS_ACTION_DOOR_PROPERTY        142
#define IDD_METAROOM_BACKGROUND         143
#define IDS_ACTION_SET_METAROOM_BACKGROUND 143
#define IDD_BACKGROUND_FILE             144
#define IDS_ACTION_ADD_METAROOM_BACKGROUND 144
#define IDS_ACTION_REMOVE_METAROOM_BACKGROUND 145
#define IDD_WORLD_SIZE                  145
#define IDS_ACTION_MULTIPLE             146
#define IDD_OPTIONS                     146
#define IDS_ACTION_CHANGE_METAROOM_BACKGROUND 147
#define IDD_SWITCH_METAROOM             147
#define IDS_ACTION_WORLD_SIZE           148
#define IDD_CA_PROPERTIES               148
#define IDS_SAVING_TO_GAME              149
#define IDS_CURRENT_POINT               150
#define IDI_ICON1                       151
#define IDS_LOADING_FROM_GAME           151
#define IDD_FLOOR_VALUES                152
#define IDS_ACTION_SET_METAROOM_MUSIC   152
#define IDD_MUSIC                       153
#define IDS_ACTION_SET_ROOM_MUSIC       153
#define IDS_SAVING_TO_GAME_ADDON        154
#define IDR_TOOLBAR1                    155
#define IDD_HEIGHT_CHECK                157
#define IDC_BULB                        1000
#define IDC_PROPERTY_TYPES_LIST         1001
#define IDC_STARTUP                     1001
#define IDC_EDIT                        1002
#define IDC_NEXTTIP                     1002
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_NAME                        1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_TIPSTRING                   1004
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_MIN                         1005
#define IDC_MAX                         1006
#define IDC_ENUMERATED                  1007
#define IDC_ENUM_VALUES                 1008
#define IDC_PROPERTY_LIST               1012
#define IDC_DROP_BUTTON                 1015
#define IDC_COMBO1                      1017
#define IDC_LIST1                       1018
#define IDC_BACKGROUND                  1018
#define IDC_ROOM_TYPE                   1018
#define IDC_SPIN                        1019
#define IDC_CA_PROPERTIES               1019
#define IDC_LIST                        1021
#define IDC_PROPERTIES                  1022
#define IDC_REMOVE                      1023
#define IDC_ADD                         1024
#define IDC_SOURCE                      1026
#define IDC_BUTTON1                     1027
#define IDC_SET                         1028
#define IDC_WIDTH                       1029
#define IDC_HEIGHT                      1030
#define IDC_MAKE_SPRITE_FILE            1031
#define IDC_METAROOM_BASE               1031
#define IDC_MAKE_PREVIEW_FILE           1032
#define IDC_ROOM_BASE                   1032
#define IDC_PREVIEW                     1033
#define IDC_VALIDATION                  1035
#define IDC_VALIDATION2                 1036
#define IDC_DISPLAY_MAP                 1036
#define IDC_VALIDATION3                 1037
#define IDC_METAROOM                    1037
#define IDC_GAIN                        1038
#define IDC_LOSS                        1039
#define IDC_X                           1039
#define IDC_DIFFUSION                   1040
#define IDC_CALCULATE                   1040
#define IDC_Y                           1041
#define IDC_MUSIC                       1042
#define IDC_MIN_PERM                    1043
#define IDC_MIN_HEIGHT                  1044
#define ID_TOOLS_ADD_ROOM               32771
#define ID_TOOLS_SELECT_ROOM            32772
#define ID_TOOLS_SELECT_METAROOM        32773
#define ID_TOOLS_ADD_METAROOM           32774
#define ID_EDIT_DELETE                  32784
#define ID_VIEW_PROPERTIES              32785
#define ID_TOOLS_ZOOM                   32786
#define ID_FILE_PROPERTY_TYPES          32787
#define ID_VIEW_ZOOM_WORLD              32788
#define ID_VIEW_ZOOM_LAST               32791
#define ID_VIEW_ZOOM_FORWARD            32792
#define ID_VIEW_ZOOM_OUT                32793
#define ID_VIEW_ZOOM_IN                 32794
#define ID_EDIT_BACKGROUND              32795
#define ID_FILE_SAVETOGAME              32796
#define ID_FILE_SAVE_TO_GAME            32797
#define ID_FILE_WORLD_SIZE              32798
#define ID_FILE_VALIDATE                32799
#define ID_TOOLS_OPTIONS                32800
#define ID_TOOLS_SET_METAROOM_IN_GAME   32801
#define ID_FILE_CA_RATES                32802
#define ID_VIEW_COLOURROOMS_CA0         32803
#define ID_VIEW_COLOURROOMS_CA1         32804
#define ID_VIEW_COLOURROOMS_CA2         32805
#define ID_VIEW_COLOURROOMS_CA3         32806
#define ID_VIEW_COLOURROOMS_CA4         32807
#define ID_VIEW_COLOURROOMS_CA5         32808
#define ID_VIEW_COLOURROOMS_CA6         32809
#define ID_VIEW_COLOURROOMS_CA7         32810
#define ID_VIEW_COLOURROOMS_CA8         32811
#define ID_VIEW_COLOURROOMS_CA9         32812
#define ID_VIEW_COLOURROOMS_CA10        32813
#define ID_VIEW_COLOURROOMS_CA11        32814
#define ID_VIEW_COLOURROOMS_CA12        32815
#define ID_VIEW_COLOURROOMS_CA13        32816
#define ID_VIEW_COLOURROOMS_CA14        32817
#define ID_VIEW_COLOURROOMS_CA15        32818
#define ID_VIEW_COLOURROOMS_CA16        32819
#define ID_VIEW_COLOURROOMS_CA17        32820
#define ID_VIEW_COLOURROOMS_CA18        32821
#define ID_VIEW_COLOURROOMS_CA19        32822
#define ID_TOOLS_CHEESE                 32823
#define ID_TOOLS_STEPCA                 32824
#define ID_VIEW_SHOW_BACKGROUND         32825
#define ID_TOOLS_RUN_CA                 32826
#define ID_TOOLS_UPDATE_CA_FROM_GAME    32829
#define ID_VIEW_DATA_BARS               32831
#define ID_VIEW_DATA_COLOURS            32832
#define ID_EDIT_FLOORCEILINGVALUES      32835
#define ID_EDIT_MUSIC                   32836
#define ID_FILE_LOADFROMGAME            32837
#define ID_FILE_SAVETOBOOTSTRAPMAPCOS   32840
#define ID_EDIT_CHECKHEIGHTS            32847
#define ID_FILE_SAVETOBOOTSTRAPADDONCOS 32848
#define ID_FILE_SAVE_TO_GAME_ADDON      32849
#define ID_HELP_CONTENTS                32851
#define ID_CDN_WEBSITE                  32852

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        159
#define _APS_NEXT_COMMAND_VALUE         32853
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           113
#endif
#endif
