#include <string>

const char* dictionary = "acbdefghi jklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!\"£$%^&*()-=_+,./<>?;'#:@~[]{}`¬\\|\n";
const char*    encdict = "JKLMacb?;'#:@~[defpqrstuvwxyzABC3456=_+,.]{}`¬\\|DEFG HIghijklmnoNOPQR/<>STUVW789!\"£$%^&*()-XYZ012¦";

const std::string unc = dictionary;
const std::string enc = encdict;

std::string quoteString(std::string source)
{
	std::string ret;
	for(int i=0;i<source.length(); i++)
		switch(source[i])
		{
		case '\\': ret += "\\\\"; break;
		case '\"': ret += "\\\""; break;
		default:
			ret += source[i];
		}
	return ret;
}

inline void encode(std::string& s)
{
	for(int i=0;i<s.length();i++)
		s[i] = enc[ unc.find( s[i] ) ];
}

inline void decode(std::string& s)
{
	for(int i=0;i<s.length();i++)
		s[i] = unc[ enc.find( s[i] ) ];
}


void emit(std::string user, std::string quote)
{
	encode(user);encode(quote);

	printf("	quoteMap.insert( std::make_pair( std::string(\"%s\"), std::string(\"%s\") ) );\n",quoteString(user).c_str(),quoteString(quote).c_str());

	decode(user);decode(quote);
	//printf("	// %s says %s\n",user.c_str(),quote.c_str());
}

int main(int argc, char* argv[])
{
	printf("#ifdef _MSC_VER\n");
	printf("#pragma warning(disable:4786 4503)\n");
	printf("#endif\n\n");
	printf("// This file is autogenerated by TextCoder in the tools folder.\n\n");
	printf("int fillMap()\n");
	printf("{\n");

	emit("ashley","I'm easily tempted :)");
	emit("ashley","I didn't say I was _easy_");
	emit("ashley","Francis, mumble mumbble.... bbpppt.. mumble.... the... mummmblle?");
	emit("ashley","Here's another C-Style exception for you!");
	emit("ashley","Hokey pokey!");
	emit("ashley","This is where I start shrugging. Where's Francis?");
	emit("ashley","This shouldn't happen and since I've seen it, I must be killed.");
	emit("ashley","What does this anti-infection spray remind you of?");
	emit("ashley","Ooh hokery pokery!");

	emit("nathan","I like a good taste of Old Peculier.");
	emit("napes", "No worries mate!");
	emit("napes", "WhooHah!");
	
	emit("jon skuse","Ashley, this is a monster that eats New Zealanders.");
	emit("jon skuse","All New Zealanders are the same, Ashley.");

	emit("robert","I just do physics, okay?!");
	emit("robert","Bafffffoooooon");
	emit("robert","It's in Creature Physics.");
	emit("robert","Using the medium of....");
	emit("robert","Using the medium of fingers touching the keyboard, I will now attempt to fix this problem with hand holding.");
	emit("robert","How many times do I have to say this: the agent count must come down!");

	emit("daniel","It's all pants I tell you!");
	emit("daniel","I'm just an oddball programmer");
	emit("daniel","Once more, a call for them, we're getting a good list together... More I tell you, more.....");
	emit("daniel","Send me some more quotes!");
	emit("daniel","If they are longer than can fit in the speech bubble, then I am going to need an agent.");
	emit("daniel","Mmmmm Long Island Iced Teas.");

	// BORING COPYWRONG STOPS ME UNCOMMENTING THIS
	// emit("Arthur Dent", "What?");
	// emit("Arthur Dent", "I don't understand.");
	// emit("Arthur Dent", "Where's the tea?");
	// emit("Zaphod Beeblebrox", "That's one hoopy frood.");
	// emit("Ford Prefect", "Would you like my towel?");
	// emit("Vogon Captain", "Oh frettled gruntbuggly...\nthy micturations are to me...\nAs plurdled gabbleblotchits on a lurgid bee\nGroop I implore thee, my foonting turlingdromes.\nAnd hooptiously drangle me with crinkly bindlewurdles,\nOr I will rend thee in the gobberwarts with my blurglecruncheon, see if I don't.\n -- Prostetnic Vogon Jeltz.");

	emit("francis", "Em foo bibble space");
	emit("francis", "Fleeeeeee");
	emit("francis", "Ooook");
	emit("francis", "Bop tanana");
	emit("francis", "Sorry Ashley, I can't hear you!");

	emit("barney", "Yep, violently unhappy.");
	emit("barney", "I don't use norns, except to test my norn killer");
	emit("barney", "You couldn't express how annoyed I am with Sheep in words");

	emit("toby", "That's a beta stopper");
	emit("toby", "Oh yes!");
	emit("toby", "Superrrrb!");
	emit("toby", "Keep your mind open, but not so open that your brains fall out.");
	emit("toby", "Excerrent");
	emit("toby", "Barrytastic!");
	emit("toby", "Nnnnyess!");
	emit("toby", "Murky Buckets and Silver Plates");
	emit("toby", "Stop worrying, Ashley.");
	emit("toby", "It has to be said.");

	emit("mark", "Wayoo wan' huh?");

	emit("ceri", "woz here");

	emit("alima", "Ooooooooh");

	emit("helen", "We have to have \"it's Life Jim, but not as we know it\" as a biologist quote?");

	emit("alig", "Me don't know what going on 'ere.");
	emit("alig", "Who be dis cheeky lickle lady?");

	emit("lawyers", "Now doctor, isn't it true that when a person dies in his sleep, he doesn't know about it until the next morning?");
	emit("lawyers", "The youngest son, the twenty-year old, how old is he?");
	emit("lawyers", "Were you present when your picture was taken?");
	emit("lawyers", "Was it you or your younger brother who was killed in the war?");
	emit("lawyers", "Did he kill you?");
	emit("lawyers", "How far apart were the vehicles at the time of the collision?");
	emit("lawyers", "You were there until the time you left, is that true?");
	emit("lawyers", "How many times have you committed suicide?");
	emit("lawyers", "Are you qualified to give a urine sample?");
	
	emit("dave","Mmmmm jelly beans!");
	emit("dave","Have you got 20p for some jelly beans?!");

	emit("ben gonshaw", "I Don't do Saturdays!");

	emit("dobbs", "Allrriiigghhhttyy!");
	emit("dobbs", "I'll be in touch later...");

	emit("ollie", "Crackerjack timing boy");

	emit("thadf", "I'm not arrogant, I'm right.");

	emit("jake", "Tractor!");
	emit("jake", "A Tractor?");
	emit("jake", "Twactor?");

	emit("tom wits", "Never could stand that damned dog");
	emit("tom waits", "What's he building in there?");
	
	emit("yak", "Llama's are lovely");

	emit("bluntman and chronic", "Snitchy, nitchy noonches!");

	emit("weird rose", "An unusual variant of the wild rose, this plant is infertile by all normal reproductive methods.  Instead, upon reaching normal reproductive age, it buds a gardener.  This vast physiological drain, including production of wellington boots, trowels and secateurs, is essential for it to breed.  The gardner then takes a cutting off the weird rose, walks off to find a wild rose, and grafts the weird rose onto the wild rose.  And so another generation is born.");

	emit("dma", "Doesn't Mean Anything");
	emit("modelford", "Poptastic");
	emit("gilliam", "Terry");
	emit("quilty", "You have a very interesting face");
	emit("hartman", "Do you maggots understand me?");
	emit("duke", "The possibility of physical and mental collapse is extremely real.");
	emit("batty", "That's the spirit!");
	emit("alex", "They cured me alright");
	emit("bowman", "Open the pod bay doors HAL.");
	emit("jack", "Wendy, give me the bat.");
	emit("kubrick", "Hail the late great SK.");
	emit("hal9000", "Are you quite sure?");
	emit("bob", "Is it giro day?");
	emit("frank zappa", "if we can't be free at least let's be cheap");

	emit("tao te ching", "It is not the clay the potter throws, which gives the pot its usefulness,\nbut the space within the shape, from which the pot is made.\nWithout a door, the room cannot be entered, and without windows it is dark.\nSuch is the utility of non-existence.");
	emit("tao te ching", "The sage experiences without abstraction,\nAnd accomplishes without action;\nHe accepts the ebb and flow of things,\nNurtures them, but does not own them,\nAnd lives, but does not dwell.");
	emit("tao te ching", "The ancients said, \"Accept and you become whole\",\nOnce whole, the world is as your home.");
	emit("tao te ching", "The world is shaped by the Way;\nIt cannot be shaped by the self.\nTrying to change it, you damage it;\nTrying to possess it, you lose it.");
	emit("tao te ching", "Who understands does not preach; Who preaches does not understand.");

	emit("oxfam", "Give a man a fish and you feed him for a day. Teach a man to fish and you feed him for a lifetime.");
	emit("h g wells", "When I see an adult on a bicycle, I do not despair for the future of the human race.");

	emit("why is the world round?", "***");
	emit("why is the world flat?", "###");

	emit("WrItTeN In mIxEd cApItAlS", "I'm sure you shouldn't be able to read this... but well decoded!");

	printf("	return 0;\n");
	printf("}\n\n");
	return 0;
}

