// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "creaturepicture2.h"

/////////////////////////////////////////////////////////////////////////////
// CCreaturePicture2

IMPLEMENT_DYNCREATE(CCreaturePicture2, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CCreaturePicture2 properties

short CCreaturePicture2::GetPoseCount()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CCreaturePicture2::SetPoseCount(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

short CCreaturePicture2::GetBorderStyle()
{
	short result;
	GetProperty(DISPID_BORDERSTYLE, VT_I2, (void*)&result);
	return result;
}

void CCreaturePicture2::SetBorderStyle(short propVal)
{
	SetProperty(DISPID_BORDERSTYLE, VT_I2, propVal);
}

float CCreaturePicture2::GetScale()
{
	float result;
	GetProperty(0x1, VT_R4, (void*)&result);
	return result;
}

void CCreaturePicture2::SetScale(float propVal)
{
	SetProperty(0x1, VT_R4, propVal);
}

BOOL CCreaturePicture2::GetFriction()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CCreaturePicture2::SetFriction(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

double CCreaturePicture2::GetAngle()
{
	double result;
	GetProperty(0x3, VT_R8, (void*)&result);
	return result;
}

void CCreaturePicture2::SetAngle(double propVal)
{
	SetProperty(0x3, VT_R8, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCreaturePicture2 operations

CString CCreaturePicture2::GetPoseString(short Index)
{
	CString result;
	static BYTE parms[] =
		VTS_I2;
	InvokeHelper(0x6, DISPATCH_PROPERTYGET, VT_BSTR, (void*)&result, parms,
		Index);
	return result;
}

void CCreaturePicture2::SetPoseString(short Index, LPCTSTR lpszNewValue)
{
	static BYTE parms[] =
		VTS_I2 VTS_BSTR;
	InvokeHelper(0x6, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 Index, lpszNewValue);
}

void CCreaturePicture2::SetAppearance(short HeadGenus, short HeadVariant, short BodyGenus, short BodyVariant, short LegsGenus, short LegsVariant, short ArmsGenus, short ArmsVariant, short TailGenus, short TailVariant, short EarGenus, short EarVariant, 
		short HairGenus, short HairVariant, short Sex, short Age)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 HeadGenus, HeadVariant, BodyGenus, BodyVariant, LegsGenus, LegsVariant, ArmsGenus, ArmsVariant, TailGenus, TailVariant, EarGenus, EarVariant, HairGenus, HairVariant, Sex, Age);
}

void CCreaturePicture2::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

